### ISSUE TITLE
Add support for `AssumeRoleWithWebIdentity`

### ISSUE THREAD

**Issue by mwieczorek** [hashicorp/aws-sdk-go-base#149]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I propose to extend this library with an option to pass `web identity token` in config and allow [AssumeRoleWithWebIdentity](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html) based on passed token, without any other credentials from 'AWS credentials chain'.

### Potential Library Implementation

```go
// Please provide an example Go implementation showing
// how this functionality may look within this codebase.
```

### Potential Terraform Backend/Provider Configuration

Explained in https://github.com/hashicorp/terraform-provider-aws/issues/22907

### References

https://github.com/hashicorp/terraform-provider-aws/issues/22907

**Comment by mwieczorek** [comment]
@gdavison I see there's a lot of work towards v2 of this package. 
I may not have the full context, but if you're open to reviewing and giving guidelines in a 'draft PR', I'm happy to create it.

**Comment by gdavison** [comment]
@mwieczorek, sorry I missed this. We would definitely welcome a PR. We might be slow reviewing it, unfortunately, since I'll be away and I'm the most familiar with this code

**Comment by mwieczorek** [comment]
Thanks @gdavison 
I prepared a PR. Please review it when you find time.
