### ISSUE TITLE
Bad path for shared credentials file is ignored

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [hashicorp/aws-sdk-go-base#18]
Consider the following terraform file to be used with https://github.com/terraform-providers/terraform-provider-aws:

```
provider "aws" {
  version = "2.35.0"
  region = "us-west-2"
  shared_credentials_file = "path_to_some_non_existing_file"
}
```

If there is a valid credentials file at `~/.aws/credentials`, terraform will use that instead of giving an error on the `path_to_some_non_existing_file`.

I tried to debug the problem a little bit and found out that `~/.aws/credentials` is loaded in `GetCredentialsFromSession`  when the loading of the credentials file fails.
https://github.com/hashicorp/aws-sdk-go-base/blob/91fe5671bc1bd585d180bba8954ef56d48bef22b/awsauth.go#L301

I don't totally understand the logic behind this code so unfortunately I am not able to propose a solution. `GetCredentialsFromSession`  was introduced in https://github.com/hashicorp/aws-sdk-go-base/pull/5/. @YakDriver could you please have a look?

**Comment by gdavison** [comment]
This has been resolved in v2 of `aws-sdk-go-base`
