### ISSUE TITLE
Profile is not passed to the session

### ISSUE THREAD

**Issue by mateuszmrozewski** [hashicorp/aws-sdk-go-base#19]
The following line creates options for a new session:
https://github.com/hashicorp/aws-sdk-go-base/blob/91fe5671bc1bd585d180bba8954ef56d48bef22b/session.go#L22

Profile is not being set. See documentation for options:
https://docs.aws.amazon.com/sdk-for-go/api/aws/session/#Options

This means only AWS_PROFILE environment variable is used, which works and is correct. However, a few downstream places try to set the profile. An example is S3 backend in terraform. This is reported as a problem in several issues for terraform s3 backend.

**Comment by jhuzetrackvia** [comment]
This is creating headache adopting Terraform on my team as well.

**Comment by michael-brown-somo** [comment]
Is there a workaround for this?
I have an S3 backend, I'm trying to work with a multi account environment. And I can't figure out how to apply credentials for each of the accounts. Seems like even setting keys doesn't work.

**Comment by TimJones** [comment]
Is there any movement on this issue? I'm working in a setup where the state bucket is access with a different set of credentials than the actual resources we're Terraforming and this is blocking us pretty hard.

**Comment by bflad** [comment]
The fix for this has been merged and will release with v0.5.0 of this library, for inclusion with Terraform CLI (S3 Backend) v0.13.0-rc1 and Terraform AWS Provider v3.0.0. Thanks to @nkupton for the implementation and patience. 👍
