### ISSUE TITLE
Implement End-To-End Testing for Session Handling

### ISSUE THREAD

**Issue by bflad** [hashicorp/aws-sdk-go-base#2]
## Description

The migrated code from https://github.com/github.com/terraform-providers/terraform-provider-aws never included end-to-end testing for the AWS Go SDK credential ordering and session construction. 

It should be possible to assemble testing similar to https://github.com/aws/aws-sdk-go/blob/5b6de26cd5565bb7349fc12593b83ddc5ce343e0/aws/session/session_test.go to ensure updates to this codebase do not cause unexpected behavior or regressions.

**Comment by aeschright** [comment]
First round of tests merged in #9. Still to do: cover AssumeRole and address any needed integration testing.

**Comment by bflad** [comment]
More unit testing has been added via #32 -- closing for more targeted issues, if necessary. 👍
