### ISSUE TITLE
Add AWS Session Tags & Transitive keys

### ISSUE THREAD

**Issue by robh007** [hashicorp/aws-sdk-go-base#21]
You can now use the following arguments Tags & Transitive Tag keys when assuming a role. This allows IAM policies to use these session keys and tags in policy conditions. There's an open issue to add these to the terraform AWS provider, but I don't think that can be done until the config struct is updated within this project. 

**Session tags & Transitive Tag Keys documentation**
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html#id_session-tags_role-chaining

- https://github.com/terraform-providers/terraform-provider-aws/issues/10994

**Comment by bflad** [comment]
I will try looking into this as part of some other work happening in this library. 👍
