### ISSUE TITLE
Enable and Return Config.CredentialsChainVerboseErrors

### ISSUE THREAD

**Issue by bflad** [hashicorp/aws-sdk-go-base#25]
## Version

```
v0.5.0
```

## Description

Not enabling `Config.CredentialsChainVerboseErrors` can lead to confusing error messaging for operators:

```
Failed to save state: Failed to upload state: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

```
* provider.aws.us-west-2: error validating provider credentials: error calling sts:GetCallerIdentity: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

It would be great if we instead enabled those verbose errors at the bottom of our error message context.

## References

* https://github.com/terraform-providers/terraform-provider-aws/issues/1307
* https://github.com/terraform-providers/terraform-provider-aws/issues/6462

**Comment by gdavison** [comment]
Closed by #63
