### ISSUE TITLE
Build fails with SECURITY ERROR

### ISSUE THREAD

**Issue by wlami** [hashicorp/aws-sdk-go-base#309]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Environment and Versions

* Terraform Executor: Local workstation

### Expected Behavior
`make tools` should run without errors. 

### Actual Behavior

Error message 
```
cd tools && go install github.com/golangci/golangci-lint/cmd/golangci-lint
verifying github.com/blizzy78/varnamelen@v0.6.1/go.mod: checksum mismatch
        downloaded: h1:mGBHm+Uo4e8JnZEKHRoZgVEOQdSBdQfY/x+k4NAXBWA=
        go.sum:     h1:zy2Eic4qWqjrxa60jG34cfL0VXcSwzUrIx68eJPb4Q8=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

```

What actually happened?
Make target fails - no local development possible.

### Steps to Reproduce

1. `make tools`

### Debug Output

Gist: https://gist.github.com/wlami/e10e6a91edb491eea08ed39f50bc70bf

### References

This is a known bug in https://github.com/blizzy78/varnamelen/issues/13#issuecomment-1079040934 - bumping varnamelen to v0.6.2 fixes the issue. This is addressed in the PR https://github.com/hashicorp/aws-sdk-go-base/pull/283 which bumps github.com/golangci/golangci-lint from 1.45.2 to 1.46.2 in /tools

**Comment by gdavison** [comment]
Thanks for reporting this, @wlami. PR #283 has been merged
