### ISSUE TITLE
[PROPOSAL] Support/Verify Shared Configuration Region

### ISSUE THREAD

**Issue by bflad** [hashicorp/aws-sdk-go-base#36]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the future we may wish to allow region configuration via the AWS shared configuration file (e.g. `~/.aws/config`), instead of requiring it via Terraform configuration or environment variables. There may be a few minor adjustments that need to happen to remove direct references to `Config.Region`, but otherwise the unit testing for `GetSession()` can theoretically be used to determine this support.

There are caveats to this support though as it can be potentially ambiguous across Terraform executors with varying AWS environment setups, so in the end we may not accept downstream implementations to make the configuration optional.

### Potential Library Implementation

```go
// Updates to TestGetSession()
```

### Potential Terraform Backend/Provider Configuration

```hcl
# Potential future improvements to make the below configurations optional

terraform {
  backend "s3" {
    region = "..."
  }
}

provider "aws" {
  region = ""
}
```

### References

- https://github.com/hashicorp/terraform/issues/15103
- https://github.com/terraform-providers/terraform-provider-aws/issues/7750
- https://github.com/terraform-providers/terraform-provider-aws/issues/4503
- https://github.com/terraform-providers/terraform-provider-aws/issues/1767
- https://github.com/terraform-providers/terraform-provider-aws/issues/687
- https://github.com/terraform-providers/terraform-provider-aws/issues/204
- https://github.com/terraform-providers/terraform-provider-aws/issues/186

**Comment by gdavison** [comment]
Support has been added to v2 of `aws-sdk-go-base`
