### ISSUE TITLE
Error getting creds when assuming role and using fallback credentials

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/aws-sdk-go-base#4]
Related issues:
* terraform-providers/terraform-provider-aws#8242
* terraform-providers/terraform-provider-aws#8052
* terraform-providers/terraform-provider-aws#6566
* terraform-providers/terraform-provider-aws#6424
* terraform-providers/terraform-provider-aws#5592
* terraform-providers/terraform-provider-aws#2420

Currently, session-derived credentials are obtained _after_ execution has passed the assume role logic.

**Currently** Session-derived creds _without_ profile:
```
GetSession()
    |
    |---> GetSessionOptions()
            |
            |---> GetCredentials()
            |       |
            |       |---> ASSUME ROLE (starting awsauth.go:233)
            |
            |--- SESSION-DERIVED CREDS OBTAINED, if no profile (session.go:49)
```

**Currently** Session-derived creds _with_ profile:
```
GetSession()
    |
    |---> GetSessionOptions()
    |       |
    |       |---> GetCredentials()
    |       |       |
    |       |       |---> ASSUME ROLE (starting awsauth.go:233)
    |       |
    |       |--- Profile set (session.go:59)
    |       
    |--- SESSION-DERIVED CREDS OBTAINED, if profile (session.go:94)
```

Specific resultant issue:
* On the `awsauth.go` path, you _cannot_ assume a role if your credentials come from a credential process. However, you _can_ assume a role if your credentials come from a shared credentials profile.

The error that you can expect to see:
```
Error: Error refreshing state: 1 error(s) occurred:

* provider.aws: No valid credential sources found for AWS Provider.
  Please see https://terraform.io/docs/providers/aws/index.html for more information on
  providing credentials for the AWS Provider
```

**Comment by YakDriver** [comment]
# Testing Results

## `credential_process` credentials _without_ `assume_role` 

```hcl
provider "aws" {
  profile = "credproc"
  region  = "us-east-1"
}
```

This works.

Here the shared credentials file has something along these lines:

```
[credproc]
credential_process = /some/process/that/returns/creds
```

## Regular credentials _with_ assume_role

```hcl
provider "aws" {
  profile = "default"
  region  = "us-east-1"

  assume_role {
    role_arn     = "arn:aws:iam::<ACCOUNT ID>:role/<ROLE NAME>"
    session_name = "<SESSION NAME>"
    external_id  = "<EXTERNAL ID>"
  }
}
```

This works.

## Credential process _with_ assume role

```hcl
provider "aws" {
  profile = "**credproc**"
  region  = "us-east-1"

  assume_role {
    role_arn     = "arn:aws:iam::<ACCOUNT ID>:role/<ROLE NAME>"
    session_name = "<SESSION NAME>"
    external_id  = "<EXTERNAL ID>"
  }
}
```

This fails and gives this error:

```console
$ terraform apply

Error: Error refreshing state: 1 error(s) occurred:

* provider.aws: No valid credential sources found for AWS Provider.
  Please see https://terraform.io/docs/providers/aws/index.html for more information on
  providing credentials for the AWS Provider
```

The corresponding AWS CLI command _does_ work:

```console
$ aws sts assume-role --role-arn arn:aws:iam::<ACCOUNT ID>:role/<ROLE NAME> --external-id <EXTERNAL ID> --role-session-name <SESSION NAME> --profile **credproc**
```

**Comment by YakDriver** [comment]
I'm making an effort to collect the credential tests in a quick and dirty repo. I think this will help inform an eventual solution. If you have something that's not working, it's easy to add a new test based on the existing set: https://github.com/YakDriver/terraform-cred-tests

**Comment by scalp42** [comment]
I can confirm @YakDriver seeing the same situation regarding all the scenarios you showed.

**Comment by evandam** [comment]
Confirming the same as @YakDriver and @scalp42 here.

**Comment by danielov1** [comment]
Is this issue resolved?
