### ISSUE TITLE
Add support for http(s) proxy in AWS provider

### ISSUE THREAD

**Issue by dkronst** [hashicorp/aws-sdk-go-base#49]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In some setups, an http proxy is used (e.g. for security reasons). It, therefor, may be desirable to have the proxy set as part of the provider's configuration (and not, for example, in the environment - since it will affect the entire process and not just specific configurations).
To support this configuration option in the provider code, support for http proxy has to first be added to the aws sdk go wrapper. 

### Potential Library Implementation
For example:
```go
	if c.HTTPProxy != "" {
		proxyUrl, err := url.Parse(c.HTTPProxy)
		if err != nil {
			return nil, err
		}

		transport.Proxy = http.ProxyURL(proxyUrl)
	}
```

### Potential Terraform Backend/Provider Configuration
```hcl

provider "aws" {
   http_proxy = "http://my_proxy:8080"
   region = "cn-northwest-1"
}

```

### References

* #46 
* https://github.com/terraform-providers/terraform-provider-aws/issues/14942

**Comment by gdavison** [comment]
Closed by merging #46
