### ISSUE TITLE
Environment credential source not working for profile in shared config

### ISSUE THREAD

**Issue by bendehaan** [hashicorp/aws-sdk-go-base#52]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In https://github.com/hashicorp/aws-sdk-go-base/pull/20, some issues were fixed w.r.t. the `credential_source` option in the (shared) config file. While this PR addressed `credential_source = EcsContainer` and `credential_source = Ec2InstanceMetadata`, it seems to have missed `credential_source = Environment`.

I ran into this when I tried to hop to a different profile defined in `~/.aws/config` given keys set in the environment. I'm still not 100% sure the issue is here, but I tried to narrow it down by extending `session_test.go` with the following:
```go
		{
			Config: &Config{
				Profile: "SharedConfigurationProfile",
				Region:  "us-east-1",
			},
			Description: "config Profile shared configuration credential_source Environment",
			EnvironmentVariables: map[string]string{
				"AWS_ACCESS_KEY_ID":     MockEnvAccessKey,
				"AWS_SECRET_ACCESS_KEY": MockEnvSecretKey,
			},
			ExpectedCredentialsValue: MockStsAssumeRoleCredentials,
			ExpectedRegion:           "us-east-1",
			MockStsEndpoints: []*MockEndpoint{
				MockStsAssumeRoleValidEndpoint,
				MockStsGetCallerIdentityValidEndpoint,
			},
			SharedConfigurationFile: fmt.Sprintf(`
[profile SharedConfigurationProfile]
credential_source = Environment
role_arn = %[1]s
role_session_name = %[2]s
`, MockStsAssumeRoleArn, MockStsAssumeRoleSessionName),
		},
```

Running this test results in the following output:

```
--- FAIL: TestGetSession (8.34s)
    --- FAIL: TestGetSession/config_Profile_shared_configuration_credential_source_Environment (0.01s)
        session_test.go:951: unexpected credentials: credentials.Value{AccessKeyID:"EnvAccessKey", SecretAccessKey:"EnvSecretKey", SessionToken:"", ProviderName:"EnvProvider"}
2020/11/18 21:44:38 [INFO] AWS Auth provider used: "StaticProvider"
2020/11/18 21:44:38 [INFO] Setting custom STS endpoint: http://127.0.0.1:60784
2020/11/18 21:44:38 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2020/11/18 21:44:38 [DEBUG] Received STS API "POST" request to "/": Action=GetCallerIdentity&Version=2011-06-15
2020/11/18 21:44:38 [DEBUG] Mocked STS API responding with 200: <GetCallerIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <GetCallerIdentityResult>
   <Arn>arn:aws:iam::222222222222:user/Alice</Arn>
    <UserId>AKIAI44QH8DHBEXAMPLE</UserId>
    <Account>222222222222</Account>
  </GetCallerIdentityResult>
  <ResponseMetadata>
    <RequestId>01234567-89ab-cdef-0123-456789abcdef</RequestId>
  </ResponseMetadata>
</GetCallerIdentityResponse>
2020/11/18 21:44:38 [INFO] Setting custom STS endpoint: http://127.0.0.1:60784
2020/11/18 21:44:38 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2020/11/18 21:44:38 [DEBUG] Received STS API "POST" request to "/": Action=GetCallerIdentity&Version=2011-06-15
2020/11/18 21:44:38 [DEBUG] Mocked STS API responding with 200: <GetCallerIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <GetCallerIdentityResult>
   <Arn>arn:aws:iam::222222222222:user/Alice</Arn>
    <UserId>AKIAI44QH8DHBEXAMPLE</UserId>
    <Account>222222222222</Account>
  </GetCallerIdentityResult>
  <ResponseMetadata>
    <RequestId>01234567-89ab-cdef-0123-456789abcdef</RequestId>
  </ResponseMetadata>
</GetCallerIdentityResponse>
2020/11/18 21:44:38 [INFO] AWS Auth provider used: "StaticProvider"
2020/11/18 21:44:38 [INFO] Setting custom STS endpoint: http://127.0.0.1:60784
2020/11/18 21:44:38 [DEBUG] Trying to get account information via iam:GetUser
2020/11/18 21:44:39 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2020/11/18 21:44:39 [DEBUG] Received STS API "POST" request to "/": Action=GetCallerIdentity&Version=2011-06-15
2020/11/18 21:44:39 [DEBUG] Mocked STS API responding with 200: <GetCallerIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <GetCallerIdentityResult>
   <Arn>arn:aws:iam::222222222222:user/Alice</Arn>
    <UserId>AKIAI44QH8DHBEXAMPLE</UserId>
    <Account>222222222222</Account>
  </GetCallerIdentityResult>
  <ResponseMetadata>
    <RequestId>01234567-89ab-cdef-0123-456789abcdef</RequestId>
  </ResponseMetadata>
</GetCallerIdentityResponse>
2020/11/18 21:44:39 [INFO] AWS Auth provider used: "StaticProvider"
2020/11/18 21:44:39 [INFO] Setting custom STS endpoint: http://127.0.0.1:60784
2020/11/18 21:44:39 [INFO] Attempting to use session-derived credentials
FAIL
FAIL	github.com/hashicorp/aws-sdk-go-base	24.335s
ok  	github.com/hashicorp/aws-sdk-go-base/tfawserr	(cached)
FAIL
make: *** [test] Error 1
```

If I interpret this correctly, this means the SDK is preferring the environment variables even when they should just be used to assume a role. The regular `aws-sdk-go` does seem to handle this as expected.

Could you help diagnose this issue? I would be happy to assist in creating a PR, but like I said I'm not 100% sure the issue can  and should be solved here.

**Comment by geniousphp** [comment]
I'm not sure if my issue is related to this issue but my Terraform couldn't use the configured profile to access S3 backend

My config
```
terraform {
  backend "s3" {
    encrypt               = true
    region                = "eu-west-1"
    profile               = "terraform-state"
    bucket                = "terraform-state"
    key                   = "terraform.tsftate"
  }
}
```

I get this error 
```
Error: Error loading state: AccessDenied: Access Denied
        status code: 403, request id: MNJVMF5YTRNKY70W, host id: zNww1Mmmr3DNqkCdfoBZGZXpmA62c2IrhicjKIkvdqUyycFi0LjveGqYIHFmIzjns5lmGPwC3vA=
```

The profile is correctly configured in my .aws/credentials and this command works `aws s3 ls   --profile=terraform-state`.

Also when I clean my environment from AWS variables, Terraform can then use the configured profile

**Comment by vroad** [comment]
This is still not possible with the latest version of AWS provider (v3.42.0). If both `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are present, the provider just uses that and ignores `profile` config.

I've found a Japanese article explaining the issue here. The provider loads configuration in different order than others (AWS SDK for Go, AWS CLI, etc).
https://ngyuki.hatenablog.com/entry/2020/10/08/230858

This is the part causing problems. `profile` is not used if credentials are found in aforementioned environment variables.
https://github.com/hashicorp/aws-sdk-go-base/blob/da4108d88728fcf4f5f9df9ea817285bccf7078e/awsauth.go#L215-L243

As the author mentions, this behavior is documented though. I'm not sure if the load order difference is intentional, either.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs#authentication

If environment variable is used as credential source, the provider prints following to logs if `TF_LOG_PROVIDER` is set to trace.
```
2021-05-31T02:20:11.920Z [INFO]  provider.terraform-provider-aws_v3.42.0_x5: 2021/05/31 02:20:11 [INFO] AWS Auth provider used: "EnvProvider": timestamp=2021-05-31T02:20:11.919Z
```

**Comment by gdavison** [comment]
This has been resolved in v2 of `aws-sdk-go-base` and is supported in the AWS Provider v4
