### ISSUE TITLE
Support `AWS_ENDPOINT_URL` and friends

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/aws-sdk-go-base#602]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS have announced _Improved flexibility when configuring endpoint URLs with the AWS SDKs and tools_: https://aws.amazon.com/blogs/developer/new-improved-flexibility-when-configuring-endpoint-urls-with-the-aws-sdks-and-tools/.

Relates https://github.com/aws/aws-sdk/issues/229.
Relates https://github.com/aws/aws-sdk-go/issues/4942.
Relates: https://github.com/aws/aws-sdk-go-v2/issues/2226.

Reference: https://docs.aws.amazon.com/sdkref/latest/guide/ss-endpoints-table.html.

**Comment by gdavison** [comment]
Related to https://github.com/aws/aws-sdk-go-v2/issues/2226

**Comment by ewbankkit** [comment]
Supported in AWS SDK for Go v2 via https://github.com/aws/aws-sdk-go-v2/pull/2328.
