### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/aws-sdk-go-base#61]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please leave a helpful description of the feature request here.

Before any **v1.0.0** release we should [rename](https://github.com/github/renaming) the default repository branch from `master` to `main`.

**Comment by gdavison** [comment]
Done
