### ISSUE TITLE
Export AWS partitions and regions as Go constants

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/aws-sdk-go-base#649]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS SDK for Go v1 exports AWS partition and region names as constants in https://github.com/aws/aws-sdk-go/blob/main/aws/endpoints/defaults.go. AWS SDK for Go v2 does not export these names.
With the deprecation of AWS SDK for Go v1 and the extensive use of these constants in the Terraform AWS Provider there is the need to define them somewhere.
As these values are already in use in `internal/endpoints/endpoints.go` it seems to make sense to export these values as constants from this module.

**Comment by ewbankkit** [comment]
We could maybe generate from https://github.com/aws/aws-sdk-go-v2/blob/main/codegen/smithy-aws-go-codegen/src/main/resources/software/amazon/smithy/aws/go/codegen/endpoints.json?

**Comment by gdavison** [comment]
Related: #120
